/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.mysql.jdbc.PreparedStatement;
import database.koneksi;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class dataKeranjang extends javax.swing.JFrame {

    koneksi myobject;
    public DefaultTableModel modelTabelKeranjang;

    public dataKeranjang() {
        initComponents();

        this.setLocationRelativeTo(null);

        myobject = new koneksi();

        comboKeranjang.removeAllItems();

        modelTabelKeranjang = new DefaultTableModel();
        tableKeranjang.setModel(modelTabelKeranjang);
        modelTabelKeranjang.addColumn("ID");
        modelTabelKeranjang.addColumn("Nama");
        modelTabelKeranjang.addColumn("Jumlah");
        modelTabelKeranjang.addColumn("Harga");
        modelTabelKeranjang.addColumn("Total");
        modelTabelKeranjang.addColumn("Pembeli");
        modelTabelKeranjang.addColumn("Telp");
        modelTabelKeranjang.addColumn("Alamat");
        tampilDataKeranjang();

        try {
            Statement statement = koneksi.connect.createStatement();
            String query = "SELECT nama FROM databarang";
            ResultSet rs = statement.executeQuery(query);

            while (rs.next()) {
                String keranjang = rs.getString("nama");
                comboKeranjang.addItem(keranjang);
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comboKeranjang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNamaPembeli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerJumlah = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKeranjang = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KERANJANG");

        jLabel2.setText("Nama Barang");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboKeranjang.setToolTipText("");
        comboKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKeranjangActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah");

        txtHarga.setEditable(false);

        jLabel5.setText("Harga Barang");

        txtTotal.setEditable(false);

        jLabel6.setText("Total Harga");

        jLabel7.setText("Nama Pembeli");

        jLabel8.setText("Telepon");

        jLabel9.setText("Alamat");

        jLabel3.setText("DATA PEMBELI");

        spinnerJumlah.setToolTipText("");
        spinnerJumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerJumlahStateChanged(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKeranjangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKeranjang);

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txtTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txtNamaPembeli))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txtTelepon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txtAlamat))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(comboKeranjang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(spinnerJumlah))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txtHarga))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(8, 8, 8)
                        .addComponent(jButton2)))
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilDataKeranjang() {
        try {
            modelTabelKeranjang.getDataVector().removeAllElements();
            modelTabelKeranjang.fireTableDataChanged();

            java.sql.PreparedStatement query = myobject.connect.prepareStatement("SELECT * FROM datakeranjang");
            ResultSet data = query.executeQuery();
            while (data.next()) {
                Object[] kolom = new Object[8];
                kolom[0] = data.getString("idkeranjang");
                kolom[1] = data.getString("namabarang");
                kolom[2] = data.getString("jumlah");
                kolom[3] = data.getString("hargabarang");
                kolom[4] = data.getString("totalharga");
                kolom[5] = data.getString("namapembeli");
                kolom[6] = data.getString("notelp");
                kolom[7] = data.getString("alamat");
                modelTabelKeranjang.addRow(kolom);

            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        mainmenu mainMenuForm = new mainmenu();
        mainMenuForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKeranjangActionPerformed

        try {
            String selectedKeranjang = comboKeranjang.getSelectedItem().toString();

            String query = "SELECT harga FROM databarang WHERE nama = ?";

            java.sql.PreparedStatement preparedStatement = koneksi.connect.prepareStatement(query);
            preparedStatement.setString(1, selectedKeranjang);
            ResultSet rs = preparedStatement.executeQuery();

            if (rs.next()) {
                int harga = rs.getInt("harga");
                txtHarga.setText(String.valueOf(harga));
            } else {
                txtHarga.setText("0");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_comboKeranjangActionPerformed

    private void spinnerJumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerJumlahStateChanged

        int jumlah = (int) spinnerJumlah.getValue();
        String hargaString = txtHarga.getText();
        int harga = Integer.parseInt(hargaString);

        if (jumlah > 0) { // Check if the input is not empty
            int penjumlahan = jumlah * harga;
            txtTotal.setText(String.valueOf(penjumlahan));
        } else {
            txtTotal.setText("0"); // Handle the case where txtJumlah is empty
        }

    }//GEN-LAST:event_spinnerJumlahStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int jumlah = (int) spinnerJumlah.getValue();

        try {
            if (jumlah <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah tidak boleh kosong!");
                spinnerJumlah.requestFocus();
            } else if (txtNamaPembeli.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Pembeli belum di isi");
                txtNamaPembeli.requestFocus();
            } else if (txtTelepon.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Telepon belum di isi");
                txtTelepon.requestFocus();
            } else if (txtAlamat.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Alamat belum di isi");
                txtAlamat.requestFocus();
            } else {
                String insertQuery = "INSERT INTO datakeranjang (idkeranjang, namabarang, jumlah, hargabarang, totalharga, namapembeli, notelp, alamat) VALUES (null, ?, ?, ?, ?, ?, ?, ?)";

                java.sql.PreparedStatement simpan = koneksi.connect.prepareStatement(insertQuery);
                simpan.setString(1, comboKeranjang.getSelectedItem().toString());
                simpan.setInt(2, jumlah);
                simpan.setString(3, txtHarga.getText());
                simpan.setString(4, txtTotal.getText());
                simpan.setString(5, txtNamaPembeli.getText());
                simpan.setString(6, txtTelepon.getText());
                simpan.setString(7, txtAlamat.getText());

                simpan.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilDataKeranjang();
                spinnerJumlah.setValue(0);
                txtNamaPembeli.setText("");
                txtTelepon.setText("");
                txtAlamat.setText("");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int jumlah = (int) spinnerJumlah.getValue();

        try {
            if ((txtNamaPembeli.getText().isEmpty())
                    && (txtTelepon.getText().isEmpty())
                    && (txtAlamat.getText().isEmpty())) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu");
            } else {
                String sql = "UPDATE datakeranjang SET jumlah = ?, hargabarang = ?, totalharga = ?, namapembeli = ?, notelp = ?, alamat = ? WHERE namabarang = ?";
                java.sql.PreparedStatement ubah = myobject.connect.prepareStatement(sql);
                ubah.setString(0, (String) comboKeranjang.getSelectedItem());
                ubah.setInt(1, jumlah);
                ubah.setString(2, txtHarga.getText());
                ubah.setString(3, txtTotal.getText());
                ubah.setString(4, txtNamaPembeli.getText());
                ubah.setString(5, txtTelepon.getText());
                ubah.setString(6, txtAlamat.getText());
                ubah.setString(7, comboKeranjang.getSelectedItem().toString());

                ubah.executeUpdate();
                tampilDataKeranjang();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKeranjangMouseClicked

        int kolom = tableKeranjang.getSelectedRow();

        if (kolom != -1) {
            String namabarang = tableKeranjang.getValueAt(kolom, 1).toString();
            String jumlah = tableKeranjang.getValueAt(kolom, 2).toString();
            String harga = tableKeranjang.getValueAt(kolom, 3).toString();
            String totalharga = tableKeranjang.getValueAt(kolom, 4).toString();
            String namapembeli = tableKeranjang.getValueAt(kolom, 5).toString();
            String telepon = tableKeranjang.getValueAt(kolom, 6).toString();
            String alamat = tableKeranjang.getValueAt(kolom, 7).toString();

            comboKeranjang.setSelectedItem(namabarang);
            spinnerJumlah.setValue(Integer.parseInt(jumlah));
            txtHarga.setText(harga);
            txtTotal.setText(totalharga);
            txtNamaPembeli.setText(namapembeli);
            txtTelepon.setText(telepon);
            txtAlamat.setText(alamat);
        }
    }//GEN-LAST:event_tableKeranjangMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            if (comboKeranjang.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu");
            } else {
                String sql = "DELETE FROM datakeranjang WHERE namabarang = ?";
                java.sql.PreparedStatement hapus = myobject.connect.prepareStatement(sql);
                hapus.setString(1, (String) comboKeranjang.getSelectedItem());

                hapus.executeUpdate();
                tampilDataKeranjang();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataKeranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataKeranjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboKeranjang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerJumlah;
    private javax.swing.JTable tableKeranjang;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaPembeli;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
